#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_visual_scripting = env_modules.Clone()
env_visual_scripting.add_source_files(env.modules_sources, "*.cpp")
